### ISSUE TITLE
The plugin doesn't work in PHPStorm for Mac

### ISSUE THREAD

**Issue by qinty** [bogdananton/PhpStorm-testNameGenerator#9]
CTRL+ALT+U doesn't work on PHPStorm for Mac OS X

**Comment by bogdananton** [comment]
Please try Cmd+Alt+U, U in Mac OS X. The alternative would be to re-assign the shortcut from PHPStorm's keymap settings https://www.jetbrains.com/phpstorm/help/configuring-keyboard-shortcuts.html#d896065e298

**Comment by qinty** [comment]
Hi Bogdan,

Turns out I was using an outdated version from the PHPStorm repository (I had v 1.0). I downloaded and installed v 1.3 from the releases page and CTRL+ALT+U, U works as expected.

Btw, you should update the PHPStorm repository with the latest version.

Thanks,
George.
